-- Apply after schema.sql to persist provider provenance and location request audit.
alter table public.locations add column if not exists source text;
alter table public.locations add column if not exists provider text;
alter table public.locations add column if not exists confidence double precision;
alter table public.locations add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.family_members add column if not exists last_source text;
alter table public.family_members add column if not exists last_provider text;

create table if not exists public.location_requests (
  id bigint generated by default as identity primary key,
  member_id uuid not null references public.family_members(id) on delete cascade,
  provider text not null,
  requested_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null check (status in ('pending', 'success', 'failed')),
  error_code text,
  error_message text,
  requested_by uuid,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists location_requests_member_requested_idx
  on public.location_requests(member_id, requested_at desc);

alter table public.location_requests enable row level security;
-- Prototype-only to match the existing app's public policies. Replace with authenticated
-- family ownership policies before deployment; see README security section.
drop policy if exists "mvp location requests read" on public.location_requests;
create policy "mvp location requests read" on public.location_requests for select using (true);
drop policy if exists "mvp location requests insert" on public.location_requests;
create policy "mvp location requests insert" on public.location_requests for insert with check (true);
