-- Family Tracker MVP schema
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.family_members (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  tracking_token uuid not null unique,
  latitude double precision,
  longitude double precision,
  accuracy double precision,
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  member_id uuid not null references public.family_members(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  recorded_at timestamptz not null default now()
);

create index if not exists locations_member_recorded_idx
  on public.locations(member_id, recorded_at desc);

alter table public.family_members enable row level security;
alter table public.locations enable row level security;

-- MVP policy: public access because this is a private prototype.
-- Before public deployment, replace these with authenticated policies.
create policy "mvp family members read"
  on public.family_members for select
  using (true);

create policy "mvp family members insert"
  on public.family_members for insert
  with check (true);

create policy "mvp family members update"
  on public.family_members for update
  using (true)
  with check (true);

create policy "mvp family members delete"
  on public.family_members for delete
  using (true);

create policy "mvp locations read"
  on public.locations for select
  using (true);

create policy "mvp locations insert"
  on public.locations for insert
  with check (true);

-- Enable Realtime for dashboard refreshes.
alter publication supabase_realtime add table public.locations;
